name: Deploy Prod

on:
  push:
    branches:
      - release/prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::925785106635:role/from_terraform_access_role
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init \
          -backend-config="bucket=terraform-state-kayanuma" \
          -backend-config="key=prod/terraform.tfstate" \
          -backend-config="region=ap-northeast-1"

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve -var="environment=prod"
