name: Deploy prod

on:
  push:
    branches:
      - "release/prod"
    paths:
      - "prodelop/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/github-actions-role
          aws-region: ap-northeast-1

      - name: Build artifact
        run: |
          tar -czf app.tar.gz prodelop

      - name: Upload to S3
        run: |
          aws s3 cp app.tar.gz s3://myapp-artifact-kayanuma/prod/app.tar.gz

      - name: Deploy EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.prod_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            bash /home/ec2-user/deploy.sh prod
